# Generated by Django 2.2.28 on 2023-01-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0002_auto_20230110_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageannotation',
            old_name='image_view',
            new_name='view',
        ),
    ]
